In [12]:
import pandas as pd
import numpy as np

In [13]:
ventas_csv = "ventas.csv"
df = pd.read_csv(ventas_csv)

print(df)

       Mes  Ventas (miles)  Publicidad (cantidad de anuncios)  \
0    Enero              33                                  3   
1  Febrero              61                                  6   
2    Marzo              70                                 10   
3    Abril              82                                 13   
4     Mayo              17                                  9   
5    Junio              24                                  6   

   Precio (dolares)  
0               125  
1               115  
2               140  
3               130  
4               145  
5               140  


In [15]:
publicidad_precio = df[["Publicidad (cantidad de anuncios)", "Precio (dolares)"]]
matriz = publicidad_precio.values
matriz = matriz.astype(float)
unos = np.ones((matriz.shape[0], 1))

X = np.hstack((unos, matriz))
print(X)

[[  1.   3. 125.]
 [  1.   6. 115.]
 [  1.  10. 140.]
 [  1.  13. 130.]
 [  1.   9. 145.]
 [  1.   6. 140.]]


In [16]:
X1 = np.dot(X.T, X)
print(X1)

[[6.00000e+00 4.70000e+01 7.95000e+02]
 [4.70000e+01 4.31000e+02 6.30000e+03]
 [7.95000e+02 6.30000e+03 1.05975e+05]]
